/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomePage
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnManageSupplements = new javax.swing.JButton();
        btnManageCustomer = new javax.swing.JButton();
        btnManageWorkoutPlans = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel2 = new javax.swing.JLabel();
        bg2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        btnSummary = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        txtDONE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnSignOut = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtCusID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        btnSupReport = new javax.swing.JButton();
        btnprintOrders = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        sidepanel.setBackground(new java.awt.Color(51, 51, 51));
        sidepanel.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("BOOKER GYM");
        sidepanel.add(jLabel4);
        jLabel4.setBounds(10, 11, 137, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.lightGray);
        jLabel5.setText("__________________________________");
        sidepanel.add(jLabel5);
        jLabel5.setBounds(0, 70, 238, 25);

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("(ADMIN)");
        sidepanel.add(jLabel6);
        jLabel6.setBounds(10, 42, 70, 14);

        btnManageSupplements.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supplementary-food (1).png"))); // NOI18N
        btnManageSupplements.setText("Manage Supplements");
        btnManageSupplements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSupplementsActionPerformed(evt);
            }
        });
        sidepanel.add(btnManageSupplements);
        btnManageSupplements.setBounds(0, 220, 240, 33);

        btnManageCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/people.png"))); // NOI18N
        btnManageCustomer.setText("Manage Customers");
        btnManageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomerActionPerformed(evt);
            }
        });
        sidepanel.add(btnManageCustomer);
        btnManageCustomer.setBounds(-1, 283, 240, 33);

        btnManageWorkoutPlans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/weightlifting.png"))); // NOI18N
        btnManageWorkoutPlans.setText("Manage Workout Plans");
        btnManageWorkoutPlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageWorkoutPlansActionPerformed(evt);
            }
        });
        sidepanel.add(btnManageWorkoutPlans);
        btnManageWorkoutPlans.setBounds(-1, 343, 240, 33);

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        sidepanel.add(btnDashboard);
        btnDashboard.setBounds(-1, 164, 240, 33);
        sidepanel.add(filler1);
        filler1.setBounds(200, 164, 0, 0);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/weightlifting (1).png"))); // NOI18N
        sidepanel.add(jLabel2);
        jLabel2.setBounds(153, 11, 64, 64);

        bg2.setBackground(java.awt.Color.white);

        jLabel1.setText("Rate: ");

        txtRate.setBackground(new java.awt.Color(204, 204, 204));
        txtRate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel8.setText("Total Income: ");

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null)));

        btnSummary.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground"));
        btnSummary.setText("View Summary");
        btnSummary.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(0, 102, 102)));
        btnSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummaryActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/star (1).png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/money (1).png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel3.setText("Summary");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));

        btnOrder.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground"));
        btnOrder.setText("View Orders");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnCustomer.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground"));
        btnCustomer.setText("View Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        jLabel7.setText("OrderID");

        txtOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIDActionPerformed(evt);
            }
        });

        txtDONE.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        txtDONE.setText("Complete");
        txtDONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDONEActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Product Name", "Customer ID", "Quantity", " Price (Rs)"
            }
        ));
        jScrollPane1.setViewportView(table1);

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnSignOut.setBackground(new java.awt.Color(0, 0, 0));
        btnSignOut.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnSignOut.setForeground(new java.awt.Color(255, 255, 255));
        btnSignOut.setText("Sign out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setText("CustomerID");

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Email", "Number", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table2);

        btnSupReport.setText("Print Supplement Details");
        btnSupReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupReportActionPerformed(evt);
            }
        });

        btnprintOrders.setText("Print Completed Orders");
        btnprintOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintOrdersActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Incomplete Orders");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Customer Details");

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addComponent(btnSupReport)
                        .addGap(18, 18, 18)
                        .addComponent(btnprintOrders)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSignOut, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bg2Layout.createSequentialGroup()
                                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bg2Layout.createSequentialGroup()
                                        .addComponent(btnOrder)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDONE))
                                    .addGroup(bg2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCustomer))
                                    .addGroup(bg2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bg2Layout.createSequentialGroup()
                                                .addGap(252, 252, 252)
                                                .addComponent(btnSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(bg2Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1)
                                                .addGap(36, 36, 36)
                                                .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addGroup(bg2Layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg2Layout.createSequentialGroup()
                                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bg2Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(37, 37, 37))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg2Layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21)))))
                                .addComponent(btnSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(bg2Layout.createSequentialGroup()
                                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bg2Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg2Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49)))
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrder)
                    .addComponent(jLabel7)
                    .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDONE))
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomer))
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupReport, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprintOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        sidepanel.add(bg2);
        bg2.setBounds(250, 10, 730, 650);

        jPanel1.setBackground(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        sidepanel.add(jPanel1);
        jPanel1.setBounds(240, 0, 730, 90);

        jPanel2.add(sidepanel, java.awt.BorderLayout.CENTER);

        bg1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageSupplementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSupplementsActionPerformed
        ManageSupplement v1 = new ManageSupplement();
        setVisible(false);
        v1.setContentPane(v1.getBg1());
        v1.setTitle("Manage Supplements");
        v1.setSize(1000, 600);
        v1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        v1.setVisible(true);
    }//GEN-LAST:event_btnManageSupplementsActionPerformed

    private void btnManageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomerActionPerformed
        ManageCustomer v1 = new ManageCustomer();
        setVisible(false);
        v1.setContentPane(v1.getBg1());
        v1.setTitle("Manage Customer");
        v1.setSize(970, 500);
        v1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        v1.setVisible(true);
    }//GEN-LAST:event_btnManageCustomerActionPerformed

    private void btnManageWorkoutPlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageWorkoutPlansActionPerformed
        ManageWorkoutPlans v1 = new ManageWorkoutPlans();
        setVisible(false);
        v1.setContentPane(v1.getBg1());
        v1.setTitle("Manage Workout Plans");
        v1.setSize(970, 500);
        v1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        v1.setVisible(true);
    }//GEN-LAST:event_btnManageWorkoutPlansActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        Dashboard v1 = new Dashboard();
        setVisible(false);
        v1.setContentPane(v1.getBg1());
        v1.setTitle("DashBoard");
        v1.setSize(1005, 720);
        v1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        v1.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummaryActionPerformed
        try {
            // Establish a connection to the database
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("DataBase Connection Success");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookergym", "root", "");
            // Create a SQL query to calculate the average rating
            String query = "SELECT AVG(rate) FROM review";
            String query1 = "SELECT SUM(price) FROM history";

            // Create a PreparedStatement to execute the query
            PreparedStatement pst = conn.prepareStatement(query);
            PreparedStatement pst1 = conn.prepareStatement(query1);

            // Execute the query and get the result
            ResultSet rs = pst.executeQuery();
            ResultSet rs1 = pst1.executeQuery();

            if (rs.next()) {
                // Get the average rating
                double averageRating = rs.getDouble(1);

                // Display the average rating in the JLabel
                txtRate.setText(String.format("  %.1f", averageRating));

            }
            if (rs1.next()) {
                // Get the Total Income
                double TotalPrice = rs1.getDouble(1);

                // Display the Total Income in the JLabel
                txtTotal.setText(String.format("  Rs.%.2f/=", TotalPrice));

            }

            // Close the ResultSet, PreparedStatement, and Connection
            rs.close();
            pst.close();
            rs1.close();
            pst1.close();
            conn.close();

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSummaryActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        Login v1 = new Login();
        setVisible(false);
        v1.setContentPane(v1.getBg1());
        v1.setTitle("Login");
        v1.setSize(970, 500);
        v1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        v1.setVisible(true);
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed

        DefaultTableModel tableModel = (DefaultTableModel) table1.getModel();
        tableModel.setRowCount(0);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("DataBase Connection Success");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookergym", "root", "");
            Statement st = con.createStatement();

            String query = "SELECT *  FROM history";
            ResultSet rs = st.executeQuery(query);
            ResultSetMetaData rsmd = rs.getMetaData();

            while (rs.next()) {

                String OrderID = rs.getString("historyID");
                String name = rs.getString("supplementName");
                String CusID = rs.getString("cusID");
                String quantity = String.valueOf(rs.getString("quantity"));
                String price = String.valueOf(rs.getString("price"));
                String status = String.valueOf(rs.getString("status"));

                String tData[] = {OrderID, name, CusID, quantity, price};
                if (status.equalsIgnoreCase("Incomplete")) {
                    tableModel.addRow(tData);
                }
            }

            // Close the resources
            rs.close();
            st.close();
            con.close();
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void txtOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIDActionPerformed

    private void txtDONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDONEActionPerformed
        String OrderID = txtOrderID.getText();
        if (OrderID.isEmpty()) {
            JOptionPane.showMessageDialog(bg1, "Give the Order ID to Complete the order", "Fail", 1);

        } else {
            try {
                // Connect to the database
                Class.forName("com.mysql.cj.jdbc.Driver");
                System.out.println("DataBase Connection Success");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookergym", "root", "");

                // Prepare the Update query
                String updateQuery = "UPDATE history SET status = ? WHERE historyID = ?";
                PreparedStatement statement = con.prepareStatement(updateQuery);
                statement.setString(1, "Completed");
                statement.setString(2, OrderID);

                int rowsAffected = statement.executeUpdate();
                if (rowsAffected > 0) {
                    System.out.println("Order Status Update successfully.");
                    JOptionPane.showMessageDialog(bg1, "ORDER COMPLETED.....!!", "Success", 1);

                    Dashboard v1 = new Dashboard();
                    setVisible(false);
                    v1.setContentPane(v1.bg1);
                    v1.setTitle("Dashboard");
                    v1.setSize(1005, 720);
                    v1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    v1.setVisible(true);

                    txtOrderID.setText("");

                } else {
                    
                    System.out.println("No record found with the specified ID.");
                    JOptionPane.showMessageDialog(bg1, "No record found with the specified ID", "Error", 2);
                    txtOrderID.setText("");
                }

                // Close the resources
                statement.close();
                con.close();

            } catch (SQLException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }

        }

    }//GEN-LAST:event_txtDONEActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        String CustomerID = txtCusID.getText();
        if (CustomerID.isEmpty()) {
            JOptionPane.showMessageDialog(bg1, "Give the Customer ID View the details", "Fail", 1);

        } else {
            try {
                // Connect to the database
                Class.forName("com.mysql.cj.jdbc.Driver");
                System.out.println("DataBase Connection Success");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookergym", "root", "");

                // Prepare the query to retrieve customer information
                String selectQuery = "SELECT * FROM customer WHERE customerID = ?";
                PreparedStatement statement = con.prepareStatement(selectQuery);

                // Assuming customerID is an integer, replace with appropriate type if needed
                statement.setString(1, CustomerID);

                ResultSet resultSet = statement.executeQuery();

                // Create a DefaultTableModel to hold the data
                DefaultTableModel model = new DefaultTableModel();

                // Add columns to the model
                model.addColumn("customerName");
                model.addColumn("email");
                model.addColumn("number");
                model.addColumn("address");

                // Populate the model with data from the database
                while (resultSet.next()) {
                    String customerName = resultSet.getString("customerName");
                    String email = resultSet.getString("email");
                    String number = resultSet.getString("number");
                    String address = resultSet.getString("address");

                    model.addRow(new Object[]{customerName, email, number, address});
                }

                // Close the resources
                resultSet.close();
                statement.close();
                con.close();

                // Assuming table2 is the name of your JTable
                table2.setModel(model);

            } catch (SQLException | ClassNotFoundException | NumberFormatException ex) {
                ex.printStackTrace();
                // Handle exceptions
            }

        }
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnSupReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupReportActionPerformed
         try {
                // Connect to the database
                Class.forName("com.mysql.cj.jdbc.Driver");
                System.out.println("DataBase Connection Success");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookergym", "root", "");

                JasperDesign jDesign= JRXmlLoader.load("C:\\xampp\\htdocs\\index\\Alpha\\BookerGym\\src\\View\\ProductDetails.jrxml");
                
                String query= "select * from supplements";
                
                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);
                jDesign.setQuery(updateQuery);
                
                JasperReport jreport= JasperCompileManager.compileReport(jDesign);
                JasperPrint jprint= JasperFillManager.fillReport(jreport,null,con);
                JasperViewer.viewReport(jprint);

            } catch (SQLException | ClassNotFoundException | NumberFormatException ex) {
                ex.printStackTrace();
                // Handle exceptions
            } catch (JRException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSupReportActionPerformed

    private void btnprintOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintOrdersActionPerformed
       try {
                // Connect to the database
                Class.forName("com.mysql.cj.jdbc.Driver");
                System.out.println("DataBase Connection Success");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookergym", "root", "");

                JasperDesign jDesign= JRXmlLoader.load("C:\\xampp\\htdocs\\index\\Alpha\\BookerGym\\src\\View\\OrderReport.jrxml");
                
                String query = "SELECT * FROM history WHERE status = 'Completed'";
                
                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);
                jDesign.setQuery(updateQuery);
                
                JasperReport jreport= JasperCompileManager.compileReport(jDesign);
                JasperPrint jprint= JasperFillManager.fillReport(jreport,null,con);
                JasperViewer.viewReport(jprint);

            } catch (SQLException | ClassNotFoundException | NumberFormatException ex) {
                ex.printStackTrace();
                // Handle exceptions
            } catch (JRException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnprintOrdersActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dashboard ui = new Dashboard();
                ui.setContentPane(ui.bg1);
                ui.setTitle("DashBoard");
                ui.setSize(1005, 720);
                ui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                ui.setVisible(true);
            }
        });
    }

    public JPanel getBg1() {
        return bg1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg1;
    private javax.swing.JPanel bg2;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnManageCustomer;
    private javax.swing.JButton btnManageSupplements;
    private javax.swing.JButton btnManageWorkoutPlans;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnSummary;
    private javax.swing.JButton btnSupReport;
    private javax.swing.JButton btnprintOrders;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTextField txtCusID;
    private javax.swing.JButton txtDONE;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JLabel txtRate;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
